name: allofolive
favicon: null
layout_spectrum: 0.40143095166422427
typography_spectrum: 0.9023146305698901
title: test
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5d5d5d'
    - '#ffffff'
    - '#1daeeb'
    - '#fc5b45'
    - '#000000'
  brandStrength: 0.625
  lightness: 0.11356444074772298
  saturation: 0.676710668951273
  rhythmicContrast: 0.18454816448502243
purpose: []
